# Generated by Django 4.2.11 on 2024-03-20 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('abstractbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Project.abstractbasemodel')),
                ('priority', models.CharField(choices=[('H', 'High'), ('L', 'Low'), ('N', 'Normal'), ('U', 'Urgent')], max_length=10)),
                ('status', models.CharField(choices=[('I', 'Completed'), ('P', 'Pending'), ('IP', 'In Progress')], max_length=10)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('related_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Project.project')),
            ],
            bases=('Project.abstractbasemodel',),
        ),
    ]
