# Generated by Django 4.2.11 on 2024-04-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_alter_task_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
    ]
